# Generated by Django 2.2.26 on 2024-06-14 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PDFFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('file', models.FileField(upload_to='pdfs/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('nouns', models.TextField(blank=True)),
                ('verbs', models.TextField(blank=True)),
            ],
        ),
        migrations.AddIndex(
            model_name='pdffile',
            index=models.Index(fields=['email'], name='pdfapp_pdff_email_0f1a06_idx'),
        ),
    ]
